name: spark
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_speed_dial: ^7.0.0
  flutter_quill: ^10.5.14
  provider: ^6.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
